#!/usr/bin/perl
use strict;
use warnings;
#use File::Slurp;

# Utility to add new disks to the emulator

my $VERSION = "0.3.0";
my $APPLE2JSDIR = "/home/apple2/apple2js";
my $DISKSDIR = "$APPLE2JSDIR/json/disks";
my $NUMARGS = $#ARGV + 1;

my $skiphead = 0;
my $skipfoot = 0;
my $infile   = "$DISKSDIR/index.json";
my $outfile  = "/tmp/newindex.txt";
my @buffer   = ();

print "adsk2json v$VERSION\n";
print "====================\n";
if ($NUMARGS != 3)
{
	print "Usage:\n";
	print "adisk2json <dskfile name> <category> <name>\n";
	exit 0;
}

my $DISKFILENAME = $ARGV[0];
my $FILECAT = $ARGV[1];
my $FILENAME = $ARGV[2];

chdir($APPLE2JSDIR);

#print "File = '$DISKSDIR/$DISKFILENAME.dsk'\n";

if (! -f "$DISKSDIR/$DISKFILENAME.dsk")
{
	print "File not found: '$DISKSDIR/$DISKFILENAME.dsk'\n";
	exit (1);
}

print "Converting $DISKFILENAME.dsk to $DISKFILENAME.json\n";
print "Using Category: $FILECAT\n";
print "Using Name: $FILENAME\n";

print "Does this look ok? [Y/n]: ";
my $confirm = <STDIN>;
chop ($confirm);

#print "confirm = '$confirm'\n";

if (($confirm eq "n") || ($confirm eq "N"))
{
	print "Not adding \"$FILENAME\" to index.json\n";
	exit 0;
}
print "Creating new edition:\n";
system("./bin/dsk2json -c \"$FILECAT\" -n \"$FILENAME\" \"$DISKSDIR/$DISKFILENAME.dsk\" > \"$DISKSDIR/$DISKFILENAME.json\"");
print "Adding \"$FILENAME\" to index.json:\n";
my $ShortName = substr("$DISKSDIR/$DISKFILENAME.json", 22);
#print "Shortname '$ShortName'\n";
my $templatefile = <<"END_TEMPLATE";
  },
  {
    "filename": "$ShortName",
    "name": "$FILENAME",
    "category": "$FILECAT"
  }
]
END_TEMPLATE

open(IN, '<', $infile) || die "Cannot open $infile for reading: $!";
my @FileLines = <IN>;
close IN;
pop(@FileLines);
pop(@FileLines);
push(@FileLines, $templatefile);
open(OUT, '>', $outfile) || die "Cannot open $outfile for writing: $!";
print (OUT @FileLines);
close OUT;

print "Installing the new file:\n";
system("/usr/bin/cp $outfile $infile");
print "Updating the index:\n";
system ("/home/apple2/bin/emuindex");
print "All done!\n";

#print "Template = '$templatefile'\n";

exit 0;
