#!/usr/bin/perl

# Utility to add new disks to the emulator

my $VERSION = "1.0.0";
my $APPLE2JSDIR = "/home/apple2/apple2js";
my $DISKSDIR = "$APPLE2JSDIR/json/disks";
my $NUMARGS = $#ARGV + 1;

print "adsk2json v$VERSION\n";
print "====================\n";
if ($NUMARGS != 3)
{
	print "Usage:\n";
	print "adisk2json <dskfile name> <category> <name>\n";
	exit 0;
}

my $DISKFILENAME = $ARGV[0];
my $FILECAT = $ARGV[1];
my $FILENAME = $ARGV[2];

chdir($APPLE2JSDIR);

#print "File = '$DISKSDIR/$DISKFILENAME.dsk'\n";

if (! -f "$DISKSDIR/$DISKFILENAME.dsk")
{
	print "File not found: '$DISKSDIR/$DISKFILENAME.dsk'\n";
	exit (1);
}

print "Converting $DISKFILENAME.dsk to $DISKFILENAME.json\n";
print "Using Category: $FILECAT\n";
print "Using Name: $FILENAME\n";

print "Does this look ok? [Y/n]: ";
my $confirm = <STDIN>;
chop ($confirm);

#print "confirm = '$confirm'\n";

if (($confirm eq "n") || ($confirm eq "N"))
{
	print "Not adding \"$FILENAME\" to index.json\n";
	exit 0;
}
print "Adding \"$FILENAME\" to index.json:\n";
system("./bin/dsk2json -c \"$FILECAT\" -n \"$FILENAME\" \"$DISKSDIR/$DISKFILENAME.dsk\" > \"$DISKSDIR/$DISKFILENAME.json\"");
exit 0;
