#!/usr/bin/perl

### BEGIN INIT INFO
# Provides:          apple2js
# Required-Start:    $local_fs $remote_fs $network $syslog
# Required-Stop:     $local_fs $remote_fs $network $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Apple2js service 2.1.0
# Description:       Apple2js service 2.1.0
# Documentation:     https://appleii.retro-os.live/index.php/forum/our-apple-e-web-emulator-tools
# Type:              forking
# X-Interactive:     false
### END INIT INFO

# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 1, or (at your option)
# any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.

my $APPLE2JSDIR = "/home/apple2/apple2js";

my $Command = $ARGV[0];
if ($Command eq "")
{
	$Command = "NONE";
}

my $running=`ps ax|grep "npm start"|grep -v grep`;

if ($Command eq "start")
{
	if ($running eq "")
	{
		print "Starting Apple2js...\n";
		if (-f "$APPLE2JSDIR/nostart")
		{
			print "Removing $APPLE2JSDIR/nostart\n";
			# Remove the lock file if it exists
			unlink("$APPLE2JSDIR/nostart");
		}
		# Start the screen process
		system("nohup $APPLE2JSDIR/startapple2js > /tmp/Apple2jsStartup.log\&");
	}
}
elsif ($Command eq "stop")
{
	print "Stopping Apple2js process...\n";
	system("touch '$APPLE2JSDIR/nostart'");
	if ($running ne "")
	{
		# Process is running, kill it
		system("killall npm");
	}
}
elsif ($Command eq "restart")
{
	if (-f "$APPLE2JSDIR/nostart")
	{
		print("Removing $APPLE2JSDIR/nostart\n");
		unlink("$APPLE2JSDIR/nostart");
	}
	if ($running ne "")
	{
		system("killall npm");
	}
}
elsif ($Command eq "status")
{
	if ($running ne "")
	{
		print("Apple2js Server Running\n");
	}
	else
	{
		print("Apple2js Server Not Running\n");
	}
}
else
{
	print ("Uknown command '$Command'\n");
	print ("Usage: $0 {start|status|stop|restart}\n");
	exit(1);
}

exit(0);
